language: csharp
solution: VstsExtensions.sln
install:
  - nuget restore VstsExtensions.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release VstsExtensions.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./VstsExtensions.Tests/bin/Release/VstsExtensions.Tests.dll
  
